### Get all contacts
GET http://localhost:3001/contacts

### Get single contact
GET http://localhost:3001/contacts/69bdaaa01f8384799831c644

### Create contact
POST http://localhost:3001/contacts
Content-Type: application/json

{
"firstName": "John",
                  "firstName": "David",
                  "lastName": "Smith",
                  "email": "david@email.com",
                  "favoriteColor": "Black",
                  "birthday": "1994-06-18"
}

### Update (use real ID)
PUT http://localhost:3001/contacts/69bdb179529208ea3f86ba2c
Content-Type: application/json

{
                  "firstName": "John",
                  "firstName": "David2",
                  "lastName": "kARl",
                  "email": "david2@email.com",
                  "favoriteColor": "Black",
                  "birthday": "1994-06-18"
}

### Delete
DELETE http://localhost:3001/contacts/69bdb179529208ea3f86ba2c